<?php
/**
 * do not edit this file
 * the file created when composer update executed
 * @author composer
 * @date   2019-10-30
 */

namespace Uniondrug\ServiceSdk\Traits;

/**
 * Backend
 * @package Uniondrug\ServiceSdk\Exports\Backends\CaseSdk $case
 * @package Uniondrug\ServiceSdk\Exports\Backends\AiprofitNewSdk $aiprofitNew
 * @package Uniondrug\ServiceSdk\Traits
 */
trait BackendTrait
{
}
