<?php
/**
 * do not edit this file
 * the file created when composer update executed
 * @author composer
 * @date   2019-10-30
 */
namespace Uniondrug\ServiceSdk\Traits;

/**
 * Boot
 * @property \Uniondrug\ServiceSdk\Modules\AbutmentSdk $abutment
 * @property \Uniondrug\ServiceSdk\Modules\ActivitySdk $activity
 * @property \Uniondrug\ServiceSdk\Modules\AssistantSdk $assistant
 * @property \Uniondrug\ServiceSdk\Modules\AuditSdk $audit
 * @property \Uniondrug\ServiceSdk\Modules\BackOrderSdk $backOrder
 * @property \Uniondrug\ServiceSdk\Modules\BillSdk $bill
 * @property \Uniondrug\ServiceSdk\Modules\CarSdk $car
 * @property \Uniondrug\ServiceSdk\Modules\CashierSdk $cashier
 * @property \Uniondrug\ServiceSdk\Modules\CommonSdk $common
 * @property \Uniondrug\ServiceSdk\Modules\CompensateSdk $compensate
 * @property \Uniondrug\ServiceSdk\Modules\CustomerSdk $customer
 * @property \Uniondrug\ServiceSdk\Modules\CustomerserviceSdk $customerservice
 * @property \Uniondrug\ServiceSdk\Modules\DataSdk $data
 * @property \Uniondrug\ServiceSdk\Modules\DeliverSdk $deliver
 * @property \Uniondrug\ServiceSdk\Modules\DrugsSdk $drugs
 * @property \Uniondrug\ServiceSdk\Modules\EquitySdk $equity
 * @property \Uniondrug\ServiceSdk\Modules\ErpPaySdk $erpPay
 * @property \Uniondrug\ServiceSdk\Modules\EshopSdk $eshop
 * @property \Uniondrug\ServiceSdk\Modules\ExpressSdk $express
 * @property \Uniondrug\ServiceSdk\Modules\FinanceSdk $finance
 * @property \Uniondrug\ServiceSdk\Modules\GoodCenterSdk $goodCenter
 * @property \Uniondrug\ServiceSdk\Modules\GoodsReplaceSdk $goodsReplace
 * @property \Uniondrug\ServiceSdk\Modules\GoodsSdk $goods
 * @property \Uniondrug\ServiceSdk\Modules\GuaranteeSdk $guarantee
 * @property \Uniondrug\ServiceSdk\Modules\HuoJuExpressSdk $huoJuExpress
 * @property \Uniondrug\ServiceSdk\Modules\IdCardSdk $idCard
 * @property \Uniondrug\ServiceSdk\Modules\InsureSdk $insure
 * @property \Uniondrug\ServiceSdk\Modules\InvoiceSdk $invoice
 * @property \Uniondrug\ServiceSdk\Modules\JavaCashierSdk $javaCashier
 * @property \Uniondrug\ServiceSdk\Modules\JavaMerchantSdk $javaMerchant
 * @property \Uniondrug\ServiceSdk\Modules\JavaOrderquerySdk $javaOrderquery
 * @property \Uniondrug\ServiceSdk\Modules\JavaOrderSdk $javaOrder
 * @property \Uniondrug\ServiceSdk\Modules\JavaPromotecenterSdk $javaPromotecenter
 * @property \Uniondrug\ServiceSdk\Modules\JavaPromotecenterServiceSdk $javaPromotecenterService
 * @property \Uniondrug\ServiceSdk\Modules\JavaPushSdk $javaPush
 * @property \Uniondrug\ServiceSdk\Modules\JavaUserSdk $javaUser
 * @property \Uniondrug\ServiceSdk\Modules\JwtSdk $jwt
 * @property \Uniondrug\ServiceSdk\Modules\MapSdk $map
 * @property \Uniondrug\ServiceSdk\Modules\MarketingSdk $marketing
 * @property \Uniondrug\ServiceSdk\Modules\Mbs2Sdk $mbs2
 * @property \Uniondrug\ServiceSdk\Modules\MbsSdk $mbs
 * @property \Uniondrug\ServiceSdk\Modules\MerchantSdk $merchant
 * @property \Uniondrug\ServiceSdk\Modules\MessageSdk $message
 * @property \Uniondrug\ServiceSdk\Modules\MessageTaskSdk $messageTask
 * @property \Uniondrug\ServiceSdk\Modules\MoreActivitySdk $moreActivity
 * @property \Uniondrug\ServiceSdk\Modules\MoreServiceSdk $moreService
 * @property \Uniondrug\ServiceSdk\Modules\MsgSdk $msg
 * @property \Uniondrug\ServiceSdk\Modules\NotifySdk $notify
 * @property \Uniondrug\ServiceSdk\Modules\OrderSdk $order
 * @property \Uniondrug\ServiceSdk\Modules\PartnersSdk $partners
 * @property \Uniondrug\ServiceSdk\Modules\PaymentsSdk $payments
 * @property \Uniondrug\ServiceSdk\Modules\PoolSdk $pool
 * @property \Uniondrug\ServiceSdk\Modules\PrivilegeSdk $privilege
 * @property \Uniondrug\ServiceSdk\Modules\ProductSdk $product
 * @property \Uniondrug\ServiceSdk\Modules\ProjectSdk $project
 * @property \Uniondrug\ServiceSdk\Modules\PromotionBiddingSdk $promotionBidding
 * @property \Uniondrug\ServiceSdk\Modules\PromotionFinanceSdk $promotionFinance
 * @property \Uniondrug\ServiceSdk\Modules\PromotionUserSdk $promotionUser
 * @property \Uniondrug\ServiceSdk\Modules\RefundSdk $refund
 * @property \Uniondrug\ServiceSdk\Modules\ReportSdk $report
 * @property \Uniondrug\ServiceSdk\Modules\RuleSdk $rule
 * @property \Uniondrug\ServiceSdk\Modules\SchemeSdk $scheme
 * @property \Uniondrug\ServiceSdk\Modules\SettlementLogSdk $settlementLog
 * @property \Uniondrug\ServiceSdk\Modules\SettlementSdk $settlement
 * @property \Uniondrug\ServiceSdk\Modules\SettlementSheetSdk $settlementSheet
 * @property \Uniondrug\ServiceSdk\Modules\SmsSdk $sms
 * @property \Uniondrug\ServiceSdk\Modules\StagnationSdk $stagnation
 * @property \Uniondrug\ServiceSdk\Modules\TagSdk $tag
 * @property \Uniondrug\ServiceSdk\Modules\TakeSdk $take
 * @property \Uniondrug\ServiceSdk\Modules\TokenSdk $token
 * @property \Uniondrug\ServiceSdk\Modules\TradeinSdk $tradein
 * @property \Uniondrug\ServiceSdk\Modules\UdappSdk $udapp
 * @property \Uniondrug\ServiceSdk\Modules\UnionProjectSdk $unionProject
 * @property \Uniondrug\ServiceSdk\Modules\UserSdk $user
 * @property \Uniondrug\ServiceSdk\Modules\WeixinSdk $weixin
 * @property \Uniondrug\ServiceSdk\Modules\WxapiSdk $wxapi
 * @property \Uniondrug\ServiceSdk\Modules\WxMessageSdk $wxMessage
 * @property \Uniondrug\ServiceSdk\Exports\Backend $backend
 * @property \Uniondrug\ServiceSdk\Exports\Module $module
 * @property \Uniondrug\ServiceSdk\Exports\Union $union
 * @property \Uniondrug\ServiceSdk\Exports\CaseSdk $case
 * @package Uniondrug\ServiceSdk\Traits
 */
trait BootTrait {
}
