<?php
/**
 * do not edit this file
 * the file created when composer update executed
 * @author composer
 * @date   2019-10-30
 */
namespace Uniondrug\ServiceSdk\Traits;

/**
 * Union
 * @property \Uniondrug\ServiceSdk\Exports\Unions\EshopSdk $eshop
 * @property \Uniondrug\ServiceSdk\Exports\Unions\FinanceSdk $finance
 * @property \Uniondrug\ServiceSdk\Exports\Unions\ProjectSdk $project
 * @package Uniondrug\ServiceSdk\Traits
 */
trait UnionTrait {
}
