<?php
return [
    'default' => [
        'timeout' => 15,
        'consulApiTimeout' => 3,
        'hosts' => [
            "abutment" => "http://abutment.module.{{domain}}",
            "activity" => "http://activity.module.{{domain}}",
            "audit" => "http://audit.module.{{domain}}",
            "bill" => "http://bill.module.{{domain}}",
            "car" => "http://car.module.{{domain}}",
            "cashier" => "http://cashier.module.{{domain}}",
            "common" => "http://common.module.{{domain}}",
            "compensate" => "http://compensate.module.{{domain}}",
            "customer" => "http://customer.module.{{domain}}",
            "customerservice" => "http://customerservice.module.{{domain}}",
            "data" => "http://data.module.{{domain}}",
            "deliver" => "http://deliver.module.{{domain}}",
            "drugs" => "http://drugs.module.{{domain}}",
            "equity" => "http://equity.module.{{domain}}",
            "eshop.union" => "http://eshop.union.{{domain}}",
            "etl" => "http://etl.module.{{domain}}",
            "express" => "http://express.module.{{domain}}",
            "finance" => "http://finance.union.{{domain}}",
            "goodsReplace" => "http://goodsreplace.union.{{domain}}",
            "idCard" => "http://idcard.module.{{domain}}",
            "insure" => "http://insure.module.{{domain}}",
            "invoice" => "http://invoice.module.{{domain}}",
            "javaCashier" => "http://java.cashier.{{domain}}",
            "goodCenter" => "http://java.goodscenter.query.{{domain}}",
            "javaMerchant" => "http://java.merchant.mng.{{domain}}",
            "javaOrderquery" => "http://java.order.query.{{domain}}",
            "javaModule" => "http://java.order.{{domain}}",
            "erpPay" => "http://java.outer.{{domain}}",
            "javaMiddleendPromotecenter" => "http://java.promotecenter.mng.{{domain}}",
            "javaPromotecenterService" => "http://java.promotecenter.service.{{domain}}",
            "javaPush" => "http://java.push.{{domain}}",
            "javaUser" => "http://java.user.credit.{{domain}}",
            "map" => "http://map.module.{{domain}}",
            "marketing" => "http://marketing.module.{{domain}}",
            "mbs" => "http://mbs.module.{{domain}}",
            "mbs2" => "http://mbs2.module.{{domain}}",
            "merchant" => "http://merchant.module.{{domain}}",
            "message" => "http://message.module.{{domain}}",
            "moreActivity" => "http://more.activity.module.{{domain}}",
            "moreService" => "http://more.module.{{domain}}",
            "msg" => "http://msg.module.{{domain}}",
            "notify" => "http://notify.module.{{domain}}",
            "ns" => "http://ns.module.{{domain}}",
            "order" => "http://order.module.{{domain}}",
            "huoJuExpress" => "http://partners.express.module.{{domain}}",
            "partners" => "http://partners.module.{{domain}}",
            "payments" => "http://payment.module.{{domain}}",
            "pool" => "http://pool.module.{{domain}}",
            "privilege" => "http://privilege.module.{{domain}}",
            "product" => "http://product.module.{{domain}}",
            "project" => "http://project.module.{{domain}}",
            "promotionBidding" => "http://promotion.bidding.module.{{domain}}",
            "promotionFinance" => "http://promotion.finance.module.{{domain}}",
            "promotionUser" => "http://promotion.user.module.{{domain}}",
            "refund" => "http://refund.module.{{domain}}",
            "report" => "http://report.module.{{domain}}",
            "rule" => "http://rule.module.{{domain}}",
            "scheme" => "http://scheme.module.{{domain}}",
            "settlement" => "http://settlement.module.{{domain}}",
            "settlementLog" => "http://settlementlog.module.{{domain}}",
            "settlementSheet" => "http://settlementsheet.module.{{domain}}",
            "stagnation" => "http://stagnation.module.{{domain}}",
            "take" => "http://take.module.{{domain}}",
            "token" => "http://token.module.{{domain}}",
            "trace" => "http://trace.module.{{domain}}",
            "udapp" => "http://udapp.module.{{domain}}",
            "unionProject" => "http://union.project.{{domain}}",
            "user" => "http://user.module.{{domain}}",
            "weixin" => "http://wx.module.{{domain}}",
            "wxapi" => "https://wxapi.{{domain}}"
        ]
    ],
    'development' => [
        'consulApiAddress' => 'http://udsdk.uniondrug.info/v1/catalog/service',
        'domain' => 'uniondrug.info'
    ],
    'testing' => [
        'consulApiAddress' => 'http://udsdk.turboradio.cn/v1/catalog/service',
        'domain' => 'truboradio.cn'
    ],
    'release' => [
        'consulApiAddress' => 'http://udsdk.uniondrug.net/v1/catalog/service',
        'domain' => 'uniondrug.net'
    ],
    'production' => [
        'consulApiAddress' => 'http://udsdk2.uniondrug.cn/v1/catalog/service',
        'domain' => 'uniondrug.cn'
    ]
];
